/*
 * Pure Javascript Upload [VERSION]
 * An adaptation of valums ajaxupload(http://valums.com/ajax-upload/)
 * [DATE]
 * Corey Hart @ http://www.codenothing.com
 */
(function(m,n,k){function h(a,b,c){var e=-1,d=a.length;if(typeof b=="function"){c=b;b=k}if(d!==k)for(;++e<d;)c.call(b||a[e],e,a[e]);else for(e in a)if(a.hasOwnProperty(e))c.call(b||a[e],e,a[e])}function o(a){var b=a.settings.complete;if(o)o.call(a,a.settings.JSON?v(a.response):a.response);b&&b.call(a,a.response)}function p(a,b){var c=a.settings.error,e=a.settings.complete;if(c)c.call(a,b||a.response);if(e)compete.call(a,b||a.response)}function v(a){a=a||"";return m.JSON&&m.JSON.parse?m.JSON.parse(a):
eval("("+a+")")}function w(a,b,c,e){var d=this,l=[];d.files=a;d.data=b;d.action=c;d.settings=e;d.counter=0;d.read={};d.xhr=k;d.aborting=false;d.boundary="";d.response="";d.length=a.length;h(d.files,function(g,f){if(f.files&&f.files[0]){d.length+=f.files.length;h(f.files,function(j,r){r&&r.fileName&&d.readFile(r)})}else f.fileName&&d.readFile(f)});d.length=l.length;h(l,d,d.readFile)}function x(a,b,c,e){var d=this;d.files=a;d.data=b;d.action=c;d.settings=e;d.length=a.length;d.aborting=false;d.response=
[];d.pack=[];d.xhr=[];d.params();h(d.files,function(l,g){if(g.files&&g.files.length){d.length+=g.files.length;h(g.files,function(f,j){j&&j.fileName&&d.send(j)})}else if(g.fileName)d.send(g);else d.length--})}function s(a,b,c,e){var d=this,l=function(){d.load()};d.files=a;d.data=b;d.action=c;d.settings=e;d.response="";d.blank=false;d.guid=t();d.frame=y("<iframe src='javascript:false;' name='"+d.guid+"' id='"+d.guid+"' style='display:none;'></iframe>");d.form=y("<form action='"+d.action+"' method='POST' target='"+
d.guid+"' style='display:none;' enctype='multipart/form-data'></form>");h(d.files,function(g,f){if((g=f.parentNode)&&f.value){g.insertBefore(f.cloneNode(true),f);g.removeChild(f);f.name=q.prefix+ ++d.counter;d.form.appendChild(f)}});h(d.data,function(g,f){var j=n.createElement("input");j.setAttribute("type","hidden");j.setAttribute("name",g);j.setAttribute("value",f);d.form.appendChild(j)});d.frame.attachEvent?d.frame.attachEvent("onload",l):d.frame.addEventListener("load",l,false);d.form.submit();
d.form.parentNode.removeChild(d.form)}var q={action:"upload.php",prefix:"file-"},u,y=function(){var a=n.createElement("div"),b;return function(c){n.body||i.error("Document isn't ready yet");a.innerHTML=c;b=a.removeChild(a.firstChild);n.body.appendChild(b);return b}}(),t=function(){var a=(new Date).getTime();return function(){return"PureJavascriptUpload-"+ ++a}}();w.prototype={abort:function(){h(this.read,function(a,b){b.complete===false&&b.reader.abort.call(b.reader)})},readFile:function(a){var b=
this,c=new FileReader,e=t(),d=b.read[e]={file:a,name:a.fileName,reader:c,guid:e,complete:false,content:""};c.onload=function(l){d.complete=true;d.content=l.target.result;--b.length<1&&b.request()};c.onerror=c.onabort=function(){d.complete=true;if(b.aborting===false){b.aborting=true;b.abort();p(b,"Unable to read "+a.fileName)}};c.readAsBinaryString(a)},source:function(){var a=this;a.boundary="----------------------------------------"+t();var b="";h(a.read,function(c,e){c=e.file;b+="--"+a.boundary+
"\r\n";b+="Content-Disposition: form-data; name='"+q.prefix+ ++a.counter+"'; filename='"+c.fileName+"'\r\n";b+="Content-Type: "+c.type+"\r\n\r\n";b+=e.content+"\r\n"});h(a.data,function(c,e){b+="--"+a.boundary+"\r\n";b+="Content-Disposition: form-data; name="+c+"\r\n\r\n";b+=e+"\r\n"});b+="--"+a.boundary+"--\r\n";return b},request:function(){var a=this,b=a.source(),c=a.xhr=new XMLHttpRequest;c.open("POST",a.action,true);c.setRequestHeader("Content-Type","multipart/form-data; boundary="+a.boundary);
c.setRequestHeader("Content-Length",b.length);c.onreadystatechange=function(){if(c.readyState==4){a.response=c.responseText;c.status>=200&&c.status<301||c.status===304?o(a):p(a)}};a.abort=c.abort;c.sendAsBinary(b)}};x.prototype={abort:function(){h(this.xhr,function(a,b){b.readyState!==4&&b.abort()})},params:function(){var a=this,b=a.action.indexOf("?")===-1;h(a.data,function(c,e){a.action+=b?"?":"&";a.action+=c+"="+e;b=true})},send:function(a){var b=this,c=new XMLHttpRequest;b.xhr.push(c);c.open("POST",
b.action,true);c.setRequestHeader("Content-Type","multipart/form-data");c.setRequestHeader("X-Requested-With","XMLHttpRequest");c.setRequestHeader("X-File-Name",a.fileName);c.setRequestHeader("X-File-Size",a.fileSize);c.upload.onload=function(){setTimeout(function(){if(c.readyState==4){var e=c.responseText;b.response+=e;if(c.status>=200&&c.status<301||c.status===304){b.pack.push(b.settings.JSON?v(e):e);--b.length<1&&o(b,true)}else if(b.aborting===false){b.aborting=true;b.abort();p(b,e)}}else setTimeout(arguments.callee,
15)},15)};c.upload.onabort=c.upload.onerror=function(){b.aborting===false&&b.abort(c.responseText)};c.send(a)}};s.prototype={abort:function(){var a=this;if(a.frame){a.blank=true;a.frame.src="javascript:'<html></html>';";p(a,"Upload canceled")}},load:function(a){var b=this,c,e;if(b.frame.src=="javascript:'%3Chtml%3E%3C/html%3E';"||b.frame.src=="javascript:'<html></html>';")b.blank&&setTimeout(function(){b.frame&&b.frame.parentNode.removeChild(b.frame)},0);else{c=b.frame.contentDocument?b.frame.contentDocument:
m.frames[b.frame.id].document;if(!(c.readyState&&c.readyState!="complete"))if(!(c.body&&c.body.innerHTML=="false"))if(m.opera&&a!==true)setTimeout(function(){b.load(true)},100);else{if(c.XMLDocument)b.response=c.XMLDocument;else if(c.body){b.response=c.body.innerHTML;if(b.settings.JSON===true)if((e=c.body.firstChild)&&e.nodeName.toUpperCase()==="PRE"&&e.firstChild)b.response=e.firstChild.nodeValue}else b.response=c;o(b);b.blank=true;b.frame.src="javascript:'<html></html>';"}}}};var i=m.Upload=function(a,
b,c,e){var d;if(a&&!a.length)a=[a];if(e===k&&typeof c=="object"){e=c;c=k}if(typeof b=="string"){c=b;b=k}if(typeof b=="object"&&typeof b.success=="function"){e=b;b=k}a=a;b=b||{};c=c||q.action;e=e||{};if(!a||!a.length)d="No files could be found";else if(typeof c!="string"||!c.length)d="Invalid action";return d?p({response:"",settings:e},d):new u(a,b,c,e)};i.NativeUpload=!!("FileReader"in m);i.DragFiles=i.NativeUpload||!!("ondrag"in n);i.error=function(a){a=typeof a=="string"?new Error(a):a;if(fn===
k)throw a;};i.normalize=function(){u=s};i.unnormalize=function(){u=i.NativeUpload?w:i.DragFiles?x:s};i.defaults=q;i.unnormalize()})(this,this.document);
