/*
 * Pure Javascript Upload [VERSION]
 * An adaptation of valums ajaxupload(http://valums.com/ajax-upload/)
 * [DATE]
 * Corey Hart @ http://www.codenothing.com
 */
(function(i,m,g){function h(a,b,c){var e=-1,d=a.length;if(typeof b=="function"){c=b;b=g}if(d!==g)for(;++e<d;)c.call(b||a[e],e,a[e]);else for(e in a)if(a.hasOwnProperty(e))c.call(b||a[e],e,a[e])}function o(a){a=a||"";return i.JSON&&i.JSON.parse?i.JSON.parse(a):eval("("+a+")")}function p(a,b,c,e){var d=this,f=[];console.warn(d);d.files=a;d.data=b||{};d.action=c||j.action;d.settings=e||{};d.counter=0;d.read={};d.xhr=g;d.aborting=false;d.boundary="";d.response="";h(d.files,function(u,l){if(l.files&&l.files[0])h(l.files,
function(v,s){f.push(s)});else l.fileName&&f.push(l)});d.length=f.length;h(f,d,d.readFile)}function q(a,b,c,e){var d=this,f=function(){d.load()};d.files=a;d.data=b||{};d.action=c||j.action;d.settings=e||{};d.response="";d.blank=false;d.guid=n();d.frame=r("<iframe src='javascript:false;' name='"+d.guid+"' id='"+d.guid+"' style='display:none;'></iframe>");d.form=r("<form action='"+d.action+"' method='POST' target='"+d.guid+"' style='display:none;' enctype='multipart/form-data'></form>");h(d.files,d,
d.fileExtraction);h(d.data,d,d.addData);d.frame.attachEvent?d.frame.attachEvent("onload",f):d.frame.addEventListener("load",f,false);d.form.submit();d.form.parentNode.removeChild(d.form)}var j={action:"upload.php",prefix:"file-"},r=function(){var a=m.createElement("div"),b;return function(c){m.body||k.error("Document isn't ready yet");a.innerHTML=c;b=a.removeChild(a.firstChild);m.body.appendChild(b);return b}}(),n=function(){var a=(new Date).getTime();return function(){return"PureJavascriptUpload-"+
++a}}();p.prototype={abort:function(){h(this.read,function(a,b){b.complete===false&&b.reader.abort.call(b.reader)})},readFile:function(a,b){var c=this;a=new FileReader;var e=n(),d=c.read[e]={file:b,name:b.fileName,reader:a,guid:e,complete:false,content:""};a.onload=function(f){d.complete=true;d.content=f.target.result;--c.length<1&&c.request()};a.onerror=a.onabort=function(){d.complete=true;if(c.aborting===false){c.abort();c.settings.error&&c.settings.error.call(c,"Unable to read "+b.fileName)}};
a.readAsBinaryString(b)},source:function(){var a=this;a.boundary="----------------------------------------"+n();var b="";h(a.read,function(c,e){c=e.file;b+="--"+a.boundary+"\r\n";b+="Content-Disposition: form-data; name='"+j.prefix+ ++a.counter+"'; filename='"+c.fileName+"'\r\n";b+="Content-Type: "+c.type+"\r\n\r\n";b+=e.content+"\r\n"});h(a.data,function(c,e){b+="--"+a.boundary+"\r\n";b+="Content-Disposition: form-data; name="+c+"\r\n\r\n";b+=e+"\r\n"});b+="--"+a.boundary+"--\r\n";return b},request:function(){var a=
this,b=a.source(),c=a.xhr=new XMLHttpRequest;c.open("POST",a.action,true);c.setRequestHeader("Content-Type","multipart/form-data; boundary="+a.boundary);c.setRequestHeader("Content-Length",b.length);c.onreadystatechange=function(){if(c.readyState==4){a.response=c.responseText;if(c.status>=200&&c.status<301||c.status===304){if(a.settings.success)a.settings.success.call(a,a.settings.JSON?o(a.response):a.response)}else a.settings.error&&a.settings.error.call(a,a.response)}};a.abort=c.abort;c.sendAsBinary(b)}};
q.prototype={abort:function(){var a=this;if(a.frame){a.blank=true;a.frame.src="javascript:'<html></html>';";a.settings.error&&a.settings.error.call(a,"Upload canceled")}},fileExtraction:function(a,b){if((a=b.parentNode)&&b.value){a.insertBefore(b.cloneNode(true),b);a.removeChild(b);b.name=j.prefix+ ++this.counter;this.form.appendChild(b)}},addData:function(a,b){var c=m.createElement("input");c.setAttribute("type","hidden");c.setAttribute("name",a);c.setAttribute("value",b);this.form.appendChild(c)},
load:function(a){var b=this,c,e;if(b.frame.src=="javascript:'%3Chtml%3E%3C/html%3E';"||b.frame.src=="javascript:'<html></html>';")b.blank&&setTimeout(function(){b.frame&&b.frame.parentNode.removeChild(b.frame)},0);else{c=b.frame.contentDocument?b.frame.contentDocument:i.frames[b.frame.id].document;if(!(c.readyState&&c.readyState!="complete"))if(!(c.body&&c.body.innerHTML=="false"))if(i.opera&&a!==true)setTimeout(function(){b.load(true)},100);else{if(c.XMLDocument)b.response=c.XMLDocument;else if(c.body){b.response=
c.body.innerHTML;if(b.settings.JSON===true)if((e=c.body.firstChild)&&e.nodeName.toUpperCase()==="PRE"&&e.firstChild)b.response=e.firstChild.nodeValue}else b.response=c;if(b.settings.success)b.settings.success.call(b,b.settings.JSON&&typeof b.response=="string"?o(b.response):b.response);b.blank=true;b.frame.src="javascript:'<html></html>';"}}}};var k=i.Upload=function(a,b,c,e){var d;if(a&&!a.length)a=[a];if(e===g&&typeof c=="object"){e=c;c=g}if(typeof b=="string"){c=b;b=g}if(typeof b=="object"&&typeof b.success==
"function"){e=b;b=g}a=a;b=b||{};c=c||j.action;e=e||{};if(!a||!a.length)d="No files could be found";else if(typeof c!="string"||!c.length)d="Invalid action";return d?(e.error||k.error).call({response:""},d):new t(a,b,c,e)};k.NativeUpload=!!("FileReader"in i);k.error=function(a){a=typeof a=="string"?new Error(a):a;if(fn===g)throw a;};k.defaults=j;var t=k.NativeUpload?p:q})(this,this.document);
