/*
 * Pure Javascript Upload [VERSION]
 * An adaptation of valums ajaxupload(http://valums.com/ajax-upload/)
 * [DATE]
 * Corey Hart @ http://www.codenothing.com
 */
(function(f,j,h){function i(a,b,c){var d=-1,e=a.length;if(typeof b=="function"){c=b;b=h}if(e!==h)for(;++d<e;)c.call(b||a[d],d,a[d]);else for(d in a)if(a.hasOwnProperty(d))c.call(b||a[d],d,a[d])}function n(a){a=a||"";return f.JSON&&f.JSON.parse?f.JSON.parse(a):eval("("+a+")")}function g(a,b,c,d){var e=this;if(a&&!a.length)a=[a];if(d===h&&typeof c=="object"){d=c;c=h}if(typeof b=="string"){c=b;b=h}if(typeof b=="object"&&typeof b.success=="function"){d=b;b=h}e.files=a;e.data=b||{};e.action=c||k.action;
e.settings=d||{};e.counter=0;if(!e.files||!e.files.length)(e.settings.error||g.error).call(e,"No files could be found");else typeof e.action!="string"||!e.action.length?(e.settings.error||g.error).call(e,"Invalid action"):e.build()}var k={action:"",prefix:"file-"},o=function(){var a=j.createElement("div"),b;return function(c){j.body||g.error("Document isn't ready yet");a.innerHTML=c;b=a.removeChild(a.firstChild);j.body.appendChild(b);return b}}(),l=function(){var a=(new Date).getTime();return function(){return"PureUpload-"+
++a}}(),p={abort:function(){i(this.read,function(a,b){b.complete===false&&b.reader.abort.call(b.reader)})},readFile:function(a,b){var c=this;a=new FileReader;var d=l(),e=c.read[d]={file:b,name:b.fileName,reader:a,guid:d,complete:false,content:""};a.onload=function(m){e.complete=true;e.content=m.target.result;--c.length<1&&c.request()};a.onerror=a.onabort=function(){e.complete=true;if(c.aborting===false){c.abort();c.settings.error&&c.settings.error.call(c,"Unable to read "+b.fileName)}};a.readAsBinaryString(b)},
source:function(){var a=this;a.boundary="----------------------------------------"+l();var b="";i(a.read,function(c,d){c=d.file;b+="--"+a.boundary+"\r\n";b+="Content-Disposition: form-data; name='"+k.prefix+ ++a.counter+"'; filename='"+c.fileName+"'\r\n";b+="Content-Type: "+c.type+"\r\n\r\n";b+=d.content+"\r\n"});i(a.data,function(c,d){b+="--"+a.boundary+"\r\n";b+="Content-Disposition: form-data; name="+c+"\r\n\r\n";b+=d+"\r\n"});b+="--"+a.boundary+"--\r\n";return b},request:function(){var a=this,
b=a.source(),c=a.xhr=new XMLHttpRequest;c.open("POST",a.action,true);c.setRequestHeader("Content-Type","multipart/form-data; boundary="+a.boundary);c.setRequestHeader("Content-Length",b.length);c.onreadystatechange=function(){if(c.readyState==4){a.response=c.responseText;if(c.status>=200&&c.status<301||c.status===304){if(a.settings.success)a.settings.success.call(a,a.settings.JSON?n(a.response):a.response)}else a.settings.error&&a.settings.error.call(a,a.response)}};a.abort=c.abort;c.sendAsBinary(b)},
build:function(){var a=this,b=[];a.read={};a.xhr=h;a.aborting=false;i(a.files,function(c,d){if(d.files&&d.files[0])i(d.files,function(e,m){b.push(m)});else d.fileName&&b.push(d)});a.length=b.length;i(b,a,a.readFile)}},q={abort:function(){var a=this;if(a.frame){a.blank=true;a.frame.src="javascript:'<html></html>';";a.settings.error&&a.settings.error.call(a,"Upload canceled")}},fileExtraction:function(a,b){if((a=b.parentNode)&&b.value){a.insertBefore(b.cloneNode(true),b);a.removeChild(b);b.name=k.prefix+
++this.counter;this.form.appendChild(b)}},addData:function(a,b){var c=j.createElement("input");c.setAttribute("type","hidden");c.setAttribute("name",a);c.setAttribute("value",b);this.form.appendChild(c)},load:function(a){var b=this,c,d;if(b.frame.src=="javascript:'%3Chtml%3E%3C/html%3E';"||b.frame.src=="javascript:'<html></html>';")b.blank&&setTimeout(function(){b.frame&&b.frame.parentNode.removeChild(b.frame)},0);else{c=b.frame.contentDocument?b.frame.contentDocument:f.frames[b.frame.id].document;
if(!(c.readyState&&c.readyState!="complete"))if(!(c.body&&c.body.innerHTML=="false"))if(f.opera&&a!==true)setTimeout(function(){b.load(true)},100);else{if(c.XMLDocument)b.response=c.XMLDocument;else if(c.body){b.response=c.body.innerHTML;if(b.settings.JSON===true)if((d=c.body.firstChild)&&d.nodeName.toUpperCase()==="PRE"&&d.firstChild)b.response=d.firstChild.nodeValue}else b.response=c;if(b.settings.success)b.settings.success.call(b,b.settings.JSON&&typeof b.response=="string"?n(b.response):b.response);
b.blank=true;b.frame.src="javascript:'<html></html>';"}}},build:function(){var a=this,b=function(){a.load()};a.blank=false;a.guid=l();a.frame=o("<iframe src='javascript:false;' name='"+a.guid+"' id='"+a.guid+"' style='display:none;'></iframe>");a.form=o("<form action='"+a.action+"' method='POST' target='"+a.guid+"' style='display:none;' enctype='multipart/form-data'></form>");i(a.files,a,a.fileExtraction);i(a.data,a,a.addData);a.frame.attachEvent?a.frame.attachEvent("onload",b):a.frame.addEventListener("load",
b,false);a.form.submit();a.form.parentNode.removeChild(a.form)}};f.Upload=function(a,b,c,d){return new g(a,b,c,d)};f.Upload.error=g.error=function(a){a=typeof a=="string"?new Error(a):a;if(fn===h)throw a;};f.Upload.NativeUpload=g.NativeUpload=!!("FileReader"in f&&"XMLHttpRequest"in f);f.Upload.defaults=g.defaults=k;g.prototype=g.NativeUpload?p:q})(this,this.document);
