/*
 * Pure Javascript Upload [VERSION]
 * An adaptation of valums ajaxupload(http://valums.com/ajax-upload/)
 * [DATE]
 * Corey Hart @ http://www.codenothing.com
 */
(function(j,n,k){function i(a,b){var c=-1,e=a.length;if(e===k)for(c in a)b.call(a[c],c,a[c]);else for(;++c<e;)b.call(a[c],c,a[c]);return a}function r(a,b){var c=a.settings.success,e=a.settings.complete;if(c)c.call(a,b?a.pack:a.settings.JSON?w(a.response):a.response);e&&e.call(a,a.response)}function m(a,b){var c=a.settings.error,e=a.settings.complete;if(c)c.call(a,b||a.response);if(e)compete.call(a,b||a.response)}function w(a){a=a||"";return j.JSON&&j.JSON.parse?j.JSON.parse(a):eval("("+a+")")}function s(a,
b,c,e){var d=this;d.files=a;d.data=b;d.action=c;d.settings=e;d.read={};d.xhr=k;d.aborting=false;d.boundary="";d.response="";d.length=0;i(d.files,function(o,g){if(g.files&&g.files[0])i(g.files,function(l,f){if(f&&f.fileName){d.length++;d.readFile(f)}});else if(g.fileName){d.length++;d.readFile(g)}})}function x(a,b,c,e){var d=this;d.files=a;d.data=b;d.action=c;d.settings=e;d.length=0;d.aborting=false;d.response=[];d.pack=[];d.xhr=[];d.params();i(d.files,function(o,g){if(g.files&&g.files.length)i(g.files,
function(l,f){if(f&&f.fileName){d.length++;d.send(f)}});else if(g.fileName){d.length++;d.send(g)}})}function t(a,b,c,e){var d=this,o=0,g=function(){d.load()};d.files=a;d.data=b;d.action=c;d.settings=e;d.response="";d.blank=false;d.guid=u();d.frame=y("<iframe src='javascript:false;' name='"+d.guid+"' id='"+d.guid+"' style='display:none;'></iframe>");d.form=y("<form action='"+d.action+"' method='POST' target='"+d.guid+"' style='display:none;' enctype='multipart/form-data'></form>");i(d.files,function(l,
f){if((l=f.parentNode)&&f.value&&f.value!==""){l.insertBefore(f.cloneNode(true),f);l.removeChild(f);f.name=p.prefix+ ++o;d.form.appendChild(f)}});i(d.data,function(l,f){var q=n.createElement("input");q.setAttribute("type","hidden");q.setAttribute("name",l);q.setAttribute("value",f);d.form.appendChild(q)});d.frame.attachEvent?d.frame.attachEvent("onload",g):d.frame.addEventListener("load",g,false);d.form.submit();d.form.parentNode.removeChild(d.form)}var p={action:"upload.php",prefix:"file-"},z=Object.prototype.toString.call(j.opera)===
"[object Opera]",v,y=function(){var a=n.createElement("div"),b;return function(c){n.body||h.error("Document isn't ready yet");a.innerHTML=c;b=a.removeChild(a.firstChild);n.body.appendChild(b);return b}}(),u=function(){var a=(new Date).getTime();return function(){return"PureJavascriptUpload-"+ ++a}}();s.prototype={abort:function(){i(this.read,function(a,b){b.complete===false&&b.reader.abort.call(b.reader)})},readFile:function(a){var b=this,c=new FileReader,e=u(),d=b.read[e]={file:a,name:a.fileName,
reader:c,guid:e,complete:false,content:""};c.onload=function(o){d.complete=true;d.content=o.target.result;--b.length<1&&b.request()};c.onerror=c.onabort=function(){d.complete=true;if(b.aborting===false){b.aborting=true;b.abort();m(b,"Unable to read "+a.fileName)}};c.readAsBinaryString(a)},source:function(){var a=this;a.boundary="----------------------------------------"+u();var b=0,c="";i(a.read,function(e,d){e=d.file;c+="--"+a.boundary+"\r\nContent-Disposition: form-data; name='"+p.prefix+ ++b+"'; filename='"+
e.fileName+"'\r\nContent-Type: "+e.type+"\r\n\r\n"+d.content+"\r\n"});i(a.data,function(e,d){c+="--"+a.boundary+"\r\nContent-Disposition: form-data; name="+e+"\r\n\r\n"+d+"\r\n"});c+="--"+a.boundary+"--\r\n";return c},request:function(){var a=this,b=a.source(),c=a.xhr=new XMLHttpRequest;c.open("POST",a.action,true);c.setRequestHeader("Content-Type","multipart/form-data; boundary="+a.boundary);c.setRequestHeader("Content-Length",b.length);c.onreadystatechange=function(){if(c.readyState==4){a.response=
c.responseText;c.status>=200&&c.status<301||c.status===304?r(a):m(a)}};a.abort=function(){c.abort()};c.sendAsBinary(b)}};x.prototype={abort:function(){i(this.xhr,function(a,b){b.readyState!==4&&b.abort()})},params:function(){var a=this,b=a.action.indexOf("?")!==-1;i(a.data,function(c,e){a.action+=b?"&":"?";a.action+=c+"="+e;b=true})},send:function(a){var b=this,c=new XMLHttpRequest;b.xhr.push(c);c.open("POST",b.action,true);c.setRequestHeader("Content-Type","multipart/form-data");c.setRequestHeader("X-Requested-With",
"XMLHttpRequest");c.setRequestHeader("X-File-Name",a.fileName);c.setRequestHeader("X-File-Size",a.fileSize);c.upload.onload=function(){(function e(){if(c.readyState==4){var d=c.responseText;b.response+=d;if(c.status>=200&&c.status<301||c.status===304){b.pack.push(b.settings.JSON?w(d):d);--b.length<1&&r(b,true)}else if(b.aborting===false){b.aborting=true;b.abort();m(b,d)}}else setTimeout(e,15)})()};c.upload.onabort=c.upload.onerror=function(){if(b.aborting===false){b.aborting=true;b.abort();m(b,c.responseText)}};
c.send(a)}};t.prototype={abort:function(){var a=this;if(a.frame){a.blank=true;a.frame.src="javascript:'<html></html>';";m(a,"Upload canceled")}},load:function(a){var b=this,c,e;if(b.frame.src=="javascript:'%3Chtml%3E%3C/html%3E';"||b.frame.src=="javascript:'<html></html>';")b.blank&&setTimeout(function(){b.frame&&b.frame.parentNode.removeChild(b.frame)},0);else{c=b.frame.contentDocument?b.frame.contentDocument:j.frames[b.frame.id].document;if(!(c.readyState&&c.readyState!="complete"))if(!(c.body&&
c.body.innerHTML=="false"))if(z&&a!==true)setTimeout(function(){b.load(true)},100);else{if(c.XMLDocument)b.response=c.XMLDocument;else if(c.body){b.response=c.body.innerHTML;if(b.settings.JSON===true)if((e=c.body.firstChild)&&e.nodeName.toUpperCase()==="PRE"&&e.firstChild)b.response=e.firstChild.nodeValue}else b.response=c;r(b);b.blank=true;b.frame.src="javascript:'<html></html>';"}}}};var h=j.Upload=function(a,b,c,e){var d;if(a&&!a.length)a=[a];if(e===k&&typeof c=="object"){e=c;c=k}if(typeof b==
"string"){c=b;b=k}if(typeof b=="object"&&typeof b.success=="function"){e=b;b=k}a=a;b=b||{};c=c||p.action;e=e||{};if(!a||!a.length)d="No files could be found";else if(typeof c!="string"||!c.length)d="Invalid action";return d?m({response:"",settings:e},d):new v(a,b,c,e)};h.NativeUpload=!!("FileReader"in j);h.DragFiles=h.NativeUpload||!!("ondrag"in n);h.error=function(a){a=typeof a=="string"?new Error(a):a;if(fn===k)throw a;};h.normalize=function(){v=h.NativeUpload?s:t};h.unnormalize=function(){v=h.NativeUpload?
s:h.DragFiles?x:t};h.defaults=p;h.normalize()})(this,this.document);
